fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  access_denied_listener:
    json: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  param_fetcher_listener: true


