version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "8011:80"
    volumes:
      - "${PROJECT_PATH}:/www"
  mysql:
    build: ./mysql
    ports:
      - "8012:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"